# Generated by Django 5.0.4 on 2024-04-05 16:49

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_pays', models.CharField(max_length=50)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('no_of_people', models.IntegerField(verbose_name=django.db.models.fields.PositiveIntegerField)),
                ('who_owes', models.CharField(max_length=200)),
                ('payback_amount', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
